name: 🗑️ Destroy Koyeb App

on:
  workflow_dispatch:  # ✅ Só executa manualmente

env:
  DOCKER_USER: nilsonmazurchi
  SERVICE_NAME: gerenciador-tarefas

jobs:
  destroy:
    name: 🗑️ Destroy Koyeb and Docker Images
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Confirm Destruction
        run: |
          echo "⚠️  ATENÇÃO: Esta ação vai DESTRUIR a aplicação no Koyeb!"
          echo "📝 Aplicação: ${{ env.SERVICE_NAME }}"
          echo "👤 Usuário Docker: ${{ env.DOCKER_USER }}"
          echo "✅ Para continuar, confirme no GitHub"

      - name: Destroy Koyeb
        run: |
          echo "🗑️ DESTRUINDO APLICAÇÃO NO KOYEB..."
          terraform -chdir=infra init
          terraform -chdir=infra destroy -auto-approve
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}

      - name: Destroy Docker Images
        run: |
          echo "🐳 DELETANDO IMAGENS DO DOCKER HUB..."
          
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST \
            -d '{"username": "'${{ env.DOCKER_USER }}'", "password": "'${{ secrets.DOCKER_PASS }}'"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)
          
          # Deleta tags específicas
          curl -X DELETE \
            -H "Authorization: JWT $TOKEN" \
            "https://hub.docker.com/v2/repositories/${{ env.DOCKER_USER }}/${{ env.SERVICE_NAME }}/tags/latest/" \
            && echo "✅ Tag latest deletada" \
            || echo "⚠️  Tag latest não encontrada"

          echo "🎯 DESTRUIÇÃO CONCLUÍDA!"