name: 🗑️ Destroy Koyeb Application

on:
  workflow_dispatch:  # Só executa manualmente
    

env:
  DOCKER_USER: nilsonmazurchi
  SERVICE_NAME: gerenciador-tarefas

jobs:
  destroy:
    name: 🗑️ Destroy Koyeb and Docker Images
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest image info
        id: image-info
        run: |
          # Pega a última imagem do Docker Hub
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST \
            -d '{"username": "'${{ env.DOCKER_USER }}'", "password": "'${{ secrets.DOCKER_PASS }}'"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)
          
          # Busca as tags disponíveis
          TAGS=$(curl -s -H "Authorization: JWT $TOKEN" \
            "https://hub.docker.com/v2/repositories/${{ env.DOCKER_USER }}/${{ env.SERVICE_NAME }}/tags/?page_size=10")
          
          # Pega a última tag (mais recente)
          LATEST_TAG=$(echo "$TAGS" | jq -r '.results[0].name' 2>/dev/null || echo "latest")
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          
          echo "📦 Imagem a ser destruída: ${{ env.DOCKER_USER }}/${{ env.SERVICE_NAME }}:$LATEST_TAG"      

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Destroy Koyeb Resources
        run: |
          echo "🗑️ DESTRUINDO APLICAÇÃO NO KOYEB..."  
          terraform -chdir=infra init      
          terraform -chdir=infra destroy -auto-approve
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
          TF_VAR_docker_image_name: ${{ needs.build-and-push.outputs.docker_image_name }}
          TF_VAR_docker_image_tag: ${{ needs.build-and-push.outputs.docker_image_tag }}


      - name: Destroy Docker Images
        run: |
          echo "🐳 DELETANDO IMAGENS DO DOCKER HUB..."
          
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST \
            -d '{"username": "'${{ env.DOCKER_USER }}'", "password": "'${{ secrets.DOCKER_PASS }}'"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)
          
          # Deleta imagem pelo tag do run_id
          curl -X DELETE \
            -H "Authorization: JWT $TOKEN" \
            "https://hub.docker.com/v2/repositories/${{ env.DOCKER_USER }}/${{ env.SERVICE_NAME }}/tags/1.0.${{ github.run_id }}/" \
            && echo "✅ Imagem 1.0.${{ github.run_id }} deletada" \
            || echo "⚠️  Imagem 1.0.${{ github.run_id }} não encontrada"
          
          # Deleta imagem pelo SHA
          curl -X DELETE \
            -H "Authorization: JWT $TOKEN" \
            "https://hub.docker.com/v2/repositories/${{ env.DOCKER_USER }}/${{ env.SERVICE_NAME }}/tags/${{ github.sha }}/" \
            && echo "✅ Imagem ${{ github.sha }} deletada" \
            || echo "⚠️  Imagem ${{ github.sha }} não encontrada"

          # Deleta Tag LATEST
          curl -X DELETE \
            -H "Authorization: JWT $TOKEN" \
            "https://hub.docker.com/v2/repositories/${{ env.DOCKER_USER }}/${{ env.SERVICE_NAME }}/tags/latest/" \
            && echo "✅ Tag latest DELETADA" \
            || echo "⚠️  Tag latest não encontrada"
          
          echo "🎯 LIMPEZA CONCLUÍDA!"